// next_app/pages/intelligence/[slug].jsx
import supabase from '../../lib/supabaseClient';

export default function MarketProfile({ report }) {
  if (!report) {
    return <div style={styles.container}>Loading market data profile...</div>;
  }

  return (
    <div style={styles.container}>
      <header style={styles.header}>
        <span style={styles.tagline}>FRONTIER MARKET ANALYSIS</span>
        <h1 style={styles.title}>{report.location_name || report.location}</h1>
      </header>

      {/* PUBLIC PREVIEW LAYER - Market Visual Blueprint */}
      <section style={styles.previewBox}>
        <h3 style={styles.sectionTitle}>📊 Market Infographic Concept Blueprint</h3>
        <p style={styles.promptText}>"{report.infographic_prompt || 'Visual data mapping generating...'}"</p>
      </section>

      {/* MONETIZATION GATEWAY LAYER - Gated behind Whop Checkout */}
      <section style={styles.paywallBox}>
        <h3 style={styles.paywallTitle}>🔒 Institutional Deep-Dive Gated Content</h3>
        <p style={styles.paywallText}>
          Unlock deep population density vectors, complete live infrastructure mappings, 
          and predictive market analytics modeling assets for this target profile.
        </p>
        
        <a 
          href={report.whop_checkout_url || `https://whop.com{report.slug}`} 
          target="_blank" 
          rel="noopener noreferrer"
          style={styles.button}
        >
          Unlock Full Intelligence Report on Whop
        </a>
      </section>
    </div>
  );
}

// 1. GENERATE STATIC PATHS (Tells Next.js what pages exist at build time)
export async function getStaticPaths() {
  try {
    const { data: reports, error } = await supabase
      .from('market_reports')
      .select('slug');

    if (error) throw error;

    const paths = reports ? reports.map((report) => ({
      params: { slug: report.slug },
    })) : [];

    return {
      paths,
      // fallback: 'blocking' server-renders new reports generated by GitHub Actions on demand
      fallback: 'blocking', 
    };
  } catch (err) {
    console.error('Error fetching static paths:', err);
    return { paths: [], fallback: 'blocking' };
  }
}

// 2. FETCH DATA FOR SINGLE PROFILE
export async function getStaticProps({ params }) {
  try {
    const { slug } = params;
    const { data: report, error } = await supabase
      .from('market_reports')
      .select('*')
      .eq('slug', slug)
      .single();

    if (error || !report) {
      return { notFound: true }; // Safely returns clean 404 page if record is missing
    }

    return {
      props: { report },
      revalidate: 60, // Refresh cached profiles at most once every 60 seconds
    };
  } catch (err) {
    console.error('Error fetching static report props:', err);
    return { notFound: true };
  }
}

const styles = {
  container: {
    maxWidth: '800px',
    margin: '0 auto',
    padding: '40px 20px',
    fontFamily: 'system-ui, -apple-system, sans-serif',
  },
  header: {
    marginBottom: '30px',
  },
  tagline: {
    fontSize: '12px',
    fontWeight: '700',
    color: '#0066cc',
    letterSpacing: '1px',
  },
  title: {
    fontSize: '36px',
    fontWeight: '800',
    marginTop: '5px',
    color: '#1a1a1a',
  },
  previewBox: {
    backgroundColor: '#f9f9f9',
    border: '1px solid #e0e0e0',
    borderRadius: '8px',
    padding: '24px',
    marginBottom: '30px',
  },
  sectionTitle: {
    fontSize: '18px',
    fontWeight: '600',
    marginBottom: '12px',
    color: '#333',
  },
  promptText: {
    fontSize: '15px',
    fontStyle: 'italic',
    color: '#555',
    lineHeight: '1.6',
  },
  paywallBox: {
    backgroundColor: '#fff5f5',
    border: '2px dashed #ff4a4a',
    borderRadius: '8px',
    padding: '32px',
    textAlign: 'center',
  },
  paywallTitle: {
    fontSize: '20px',
    fontWeight: '700',
    color: '#d32f2f',
    marginBottom: '10px',
  },
  paywallText: {
    fontSize: '15px',
    color: '#444',
    lineHeight: '1.6',
    marginBottom: '20px',
    maxWidth: '550px',
    margin: '0 auto 20px auto',
  },
  button: {
    display: 'inline-block',
    padding: '12px 28px',
    backgroundColor: '#1a1a1a',
    color: '#fff',
    border: 'none',
    borderRadius: '6px',
    fontSize: '15px',
    fontWeight: '600',
    textDecoration: 'none',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
  },
};
